### ISSUE TITLE
Documentation: JRE 17 Support

### ISSUE THREAD

**Issue by ChuckQuinnIV** [paketo-buildpacks/adoptium#271]
The following disclaimer is present in the README.md:

> Please note that starting with Java version 16, the upstream Adoptium project has elected to [forgo JRE releases](https://adoptium.net/faq.html#jres). As such, this buildpack will only include JREs for Java 8 and 11. If you select a JRE for 16+, you'll end up with a JDK instead.

However, the FAQ link no longer references forgoing JRE releases & Adoptium seems to have Java 17 JREs released.

Is this warning still accurate / needed?

**Comment by dmikusa** [comment]
Thanks for raising this up. Looks like it's no longer accurate. We can remove that.

For what it's worth, we do have JRE releases in the buildpack so there shouldn't be a functional impact by this.

**Comment by ChuckQuinnIV** [comment]
Cheers @dmikusa - just submitted a quick PR for that change, feel free to adjust as needed!
