### ISSUE TITLE
Inconsistent adoptium version

### ISSUE THREAD

**Issue by achimbitzer** [paketo-buildpacks/adoptium#297]
The output generated during building an image using the Paketo Adoptium Buildpack is inconsistent regarding the version of the Adoptium JDK.

## Expected Behavior
I expect all ouput of the Adoptium Buildpack to reflect the actually used version of adoptium consitently.

## Current Behavior
The first line produced by  the adoptium buildpack contains Adoptium version 11.0.0:
`Paketo Buildpack for Adoptium 11.0.0`
The following lines contradict this in that they contain version 17, here are some examples:
`$BP_JVM_VERSION              17 `
`Adoptium JRE 17.0.6: Contributing to layer`
`Downloading from https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/OpenJDK17U-jre_x64_linux_hotspot_17.0.6_10.tar.gz`

The last line refers to adoptium 11.0.0 again:
`Finished running build for buildpack paketo-buildpacks/adoptium@11.0.0`

The generated image actually uses Adoptium Temurin 17, so only the first and last line are wrong.

## Possible Solution
Fix the wrong output.

## Steps to Reproduce
Build an image using Paketo Adoptium Buildpack.

## Motivations
It's misleading that the output contains different versions. To avoid misunderstandings it should only contain the correct version which is actually used.

## edit

I've added the complete output as attachment: 
[paketo-buildpack-adoptium-output-java-11-17.txt](https://github.com/paketo-buildpacks/adoptium/files/11089008/paketo-buildpack-adoptium-output-java-11-17.txt)

And I've also added more information to the section "Current Behavior".

**Comment by dmikusa** [comment]
>The first line produced by the adoptium buildpack contains Adoptium version 11.0.0:
>Paketo Buildpack for Adoptium 11.0.0
> ...
>The last line refers to adoptium 11.0.0 again:
>Finished running build for buildpack paketo-buildpacks/adoptium@11.0.0

Where you see `11`, that is the [buildpack version](https://github.com/paketo-buildpacks/adoptium/releases/tag/v11.0.0). It's just coincidental that the buildpack version happens to be 11 and so does one of the Java versions.
